version: "3.1"
services:
  dienst:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    links:
      - datenbank
      - propay

  datenbank:
    container_name: datenbank
    image: oscarfonts/h2
    volumes:
      - ./datenbank:/opt/h2-data

  propay:
    container_name: propay
    image: propra/propay
    volumes:
      - ./data:/code/data